### ISSUE TITLE
error al guardar imagen

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-cam#2]
Tiene hardcodeado /home/alumno como path para guardar imagenes.
Para obtener el directorio se tiene que usar "xdg-user-dir PICTURES"

**Comment by DiegoAccorinti** [comment]
fixed via [036baeb](https://github.com/HuayraLinux/huayra-cam/commit/036baebc08e7043a406868fc726ec2ac8ea36203)
